image: alpine:latest

stages:
  - build
  - test
  - deploy

variables:
  NODE_ENV: "development"
  APP_VERSION: "1.0.0"

build_job:
  stage: build
  image: maven:3.9
  variables:
    NODE_ENV: "production"
    APP_VERSION: "2.0.0"
  script:
    - echo "Building the project... $NODE_ENV & $APP_VERSION"
    - ls -la
    # Add your build commands here

build_job1:
  stage: build
  when: manual
  image: maven:3.9
  variables:
    NODE_ENV: "production"
    APP_VERSION: "2.0.0"

  before_script:
    - echo "Preparing environment..."

  script:
    - echo "Building the project... $NODE_ENV & $APP_VERSION"
    - ls -la
    # Add your build commands here

build_job2:
  stage: build
  needs:
    - build_job1
  image: maven:3.9
  variables:
    NODE_ENV: "production"
    APP_VERSION: "2.0.0"

  script:
    - echo "Building the project... $NODE_ENV & $APP_VERSION"
    - ls -la

  after_script:
    - echo "Cleaning up..."

    # Add your build commands here

include:
  - local: "pipeline_stages_20251231/test-job.yml"

deploy_job:
  stage: deploy
  script:
    - echo "Deploying the application... $NODE_ENV & $APP_VERSION"
    - ls -la
    # Add your deploy commands here